import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'
import { SnackbarProvider } from 'notistack'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'EBook Mania',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SnackbarProvider>
          {children}
        </SnackbarProvider>
      </body>
    </html>
  )
}