import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'
import { SnackbarProvider } from 'notistack'
import { UserProvider } from '@/common/context/userContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Bookstorm | 2024',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <SnackbarProvider>
            {children}
          </SnackbarProvider>
        </UserProvider>
      </body>
    </html>
  )
}